language: python
python:
- '2.7'
node_js:
- '0.10'
notifications:
  email:
  - tang.jilong@gmail.com
  - kkiiiu@gmail.comk
install:
- pip install virtualenv
before_script:
- echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
- base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
#- echo 'Install GeoIP API C'
#- wget -N https://github.com/maxmind/geoip-api-c/releases/download/v1.6.1/GeoIP-1.6.1.tar.gz 
#- tar -xvf GeoIP-1.6.1.tar.gz
#- cd GeoIP-1.6.1 && ./configure
#- make 
#- sudo make install
- echo 'Ready to static code verification.'
- cd /home/travis/build/cogenda/cogenda-web
- ./setenv.sh
- source venv/bin/activate
- npm install
- npm install -g grunt-cli
- make pylint 
- make jslint
#- make web-setup
#- make web
#- echo 'Ready to sync with AWS S3 and AliYun OSS.'
#- pwd && echo $COGENDA_STATIC_HOME
#- git clone --depth=50 --branch=master https://github.com/cogenda/cloud-sync.git /home/travis/build/cogenda/cloud-sync
#- cd /home/travis/build/cogenda/cloud-sync
#- ./setenv.sh
#- source venv/bin/activate
#- make travis
after_success:
- echo 'Ready to deploy to Linode production server.'
- cd /home/travis/build/cogenda/cogenda-web
- ./setenv.sh
- source venv/bin/activate
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: PTGUnUDFnKAW8ninSROEq7u9yKSDrZTOKNv7t3+V02eawANgDwnB6qmn11FUNP1tHVSWEAjh600SS7XxOThUf/GoPOa1i8SnJJnsyxMb1tB/1cEAjr/0FwwVOZq0qTjAv+44ytbaNzlzQ+S/qzUBG7ZYrm0b/yhh990kAIFS/ws=
  - secure: ED4ZsF3DydIFSI/AhVXf2SIdE/FFG+ckfRCGnP0q3SguBHYeiM2QCborrkTXDQaXbhaQNoHfdVoZQn0pC1nvKZN+nkLFt/xFL765g/ifj9BE6M2UQBJMo7NnJkAF1emTAeGmIMbYRV5MPH5Tv85opIVSamORjokmzwhMZaYkTDM=
  - secure: Co7DXOJOH0zLGdzBmrqw4fajRx683e56iXNhEGERwyOwlltwYLerU47PG4JlFByK9LzDtuf/EHB+ehgvmAYRSI0kJNYQsEMRXFmPRXTn9ZyDysOyqnAIb2QN29GyEdtYD4F7rSPVaihmxNlv279FcS5vtdQMAmnazZYBkqzldKM=
  - secure: jNmLSxlPi3sFCYLBPKDA44MTP1XFpyLhHSqgV5NhoGex7ui8NfJvOxq3WyLjXc6Vs7Tj6IB+SW9ROKVlyTuYnrI4G6nvQtzDLtj4iiQe7QUGR530ompmjkrXGMxZQGPSccjhC81EySVU5CUi5HXPiht3rA5mE4vWaHLxYg++sdc=
  - secure: KLWmY6jHbNnBsIrGI/LsEzSP2MuAhZvDfFQ7zo56zMP2dqAnYCJjtALX021Hm/1EUvfygH8YmcMWR322qUxgI56j7zOW4VyNMMFJ6X7fndY6/Z5nTuZwTZWnhTcZJpcxBQinQQpkot+xqLDRKWX7SzC6sY8j+yhsyj4RXhZmEEw=
  - secure: IXE9h1dpt4RiTD2OhT7ZPHI0kn5lXIvx3mnjuxOgIB10LUuWIHMis6LB5uI40XrgXnw63D8zmhx547/46GXuY5xbPj9620LvID8B0i+XchRGF8hUJZGAGtiyaSt4bkSTNGLpkgI0tFZkoNNbgj5BRT4XzHgznWrMWuQinfrG7JM=
  - secure: gWIr+xa5sFKS/DjNmsagN0FHkpW5dGqXsl/yGTEX3/k3JBokqJ91U56ekoYy1RpVwP/q6jRknqZPPWRBdKlTD0wnPbYdMd+Z6aovQJqTmAC9guW+IuKxgYAm8LEYmPo2eyhprYtrsvtcOUgQ6w5ArutqCiHe9cIstCFgj/2NlME=
  - secure: h5Vjgbz6ssyvYcAVdX5KKtxLVRx7G8vn9QK6la+ASFJFLAB5JnhwJZu34rEVI+YDUIxRjoBw00iV7Un6+WQroxcbZ0NTDoLwmH7dDPj6ofW6F8fm/fDVIxsmV0SiOg7wweSnYKfr7q8hjZi9SvAubFIT9py5+BiVeFJU4eDfFd8=
  - secure: DpNiS4/nJpF5sjEmclPvPSn+lRa44WqgxzjfASJve7HWaEVgGVEAWiv0Fp+IfF1huAQM6MnfYqF2HHN4haBxQhJG38uUeQ2OPg5umguFU0BTo4FAqkfgDIGlOZsWNV84MbtocGmw9OCodN2NtviO7tSohEWM1iQDCLdMocFXGL4=
  - secure: CWFkhzA6FS23UPKSAnuhfVdkgTrI4947TE27AknV8e8bC1oKe20Ob9xhW2FJ7eeJLpSvEif9SYM2v14s4gDnRgX0dVvU9Gp7Sa9GURZHBQ5/WfndsAamYT4SFgm40jAXW/H0u/1MMMcYxEA2f5zMI1DI3qxlbpvyG+LByglcEbA=
  - secure: PgBosmr4LJL52khyEp36KsnI6QqhRt1niTdHnkDriO0PyOd4ZonhiE5MDQXP3kcAXS0WWYCJgspKE15mDMkQXeSWHELmMxPd5iJls1WW8ggNMQpDMrOhj1K1bqoUkKOuFL6qtjAw+0LLV92xFFi0+O5XegozRuSTaOwSTVQt08s=
  - secure: fwEAnjQNU0iZTRST4DFw1nfReHQkAkvD21cgLNzq/0P77n1PajCeTjplC/nLGBmItK0iexoc1QNiSylrLBKn1AeJYpPe9/QuCbEzWSEnplGERj+x16neKK/0NA5wKc31X1qfT6h2lQI4/UReUSB6LiDndqB63eqaUwS6oARLCxk=
  - secure: O9i8+K5hEWufLhbPCq+uHPWUtFKkuFShwFgSamZ1G3benDiNbai//8ZMcl+gw84+n+JhkDoQ+Z3Dc/iHKsF6zom46ZSTqNvRfItg4BGHzxMAmokXatE7p/I78CntbRZtF//BxSg0+XgdQ0y7OPMW0i+6P6jxWzO7mZczV7x03ME=
  - secure: IoXx7eA3cZo/psZogtfRvT9BZqSdQAFZ7SmjBkEXMTsCnRWtQBFXncXH5E5I5hzOzLExZg7fwj4FA79LD4GwpG1mIXV4K9Y4PCQB9OvmEGBJFjae2PopE9bSwv0PwWVRfK78wLGdG+VoNBV/FYtZr8KlZ9i1SxR36bMHm/jQBSI=
  - secure: Y/6ZnQhNGJySoBHPLNvvRd/QGCH4kCaoJq/Yn6DJqHwsLSJVluVE6kVya8uYqzxEIxFI/xDODt8AjmpFqVRZrAPLLQhhn9esuydu0akXhk7uoxIUk+lu/4aZ1ooQRU192FAVr2ralfAtoMchEDzPRJl+cLpt96CoBJMkE1e16qE=
  - secure: c2GtTg4O/tc3I0siCVu9g3LeXhQhxDEiw7rFsfmKhuBWHinb+fI/mFr5cKtfEF9JUrKA4wpqd/eUvO8kiDylvNCev8YbbhHevQT6AcGvAx3ZEJDVbKBFzaiPqDeXM8fDoTjCTnhgcJ7hhTinGHAzQxlsL+pqKZgxEZSXi8LrY/0=
  - secure: Xt6q8k7nJhIkaWlOp8TpsZOFwJzHle/guh3TsYmCvHi5/M8S+5t5Au1ItKIeXhj7M48FDk1Qdm+Zh6T2dV5K1/lrStaH/8/gOBWUEk4X055C3lrEZSuuOkZcN1XNOufSHHOcMTRE+eZv/yP7rMChVyoV+hrJLU21i8jrJ3ekBYI=
  - secure: BdM14h5WNfxQffZ+kUbD7UPwjG86OWtWEfs4sefXjaJtycLP4sE7Y2IL8RDv7eQ25KSCxDDNQ/4+vVGJYfUT7zIFaodP4qadJgWkyagMtQoxaWYeJNhwEd13ixxDUJ24a2De1COQbrLpSeYXRWqias9U1w6jMispoaN3mQiW+xs=
  - secure: PoG++8qb/sSdhA97vnRn69WQ/JTr5BptyeW2OA3xDbBpPas5aPX5Kwvr+/74WHicy6262S0f4xaOFV9Ce5J8hX0DbonuM9LZRtjUKIEFoATJWHajmHqOTXC2LH+v2yhKg6KN72K6ApRBiKeUdVwkltaZ2+kmjnXBGhBdxySU8VU=
  - secure: Be/qqF71kIdirxxWtmqLESFQkTRWzhE5ExQdjClxfpP/dYifh0ZIAtXLhPvXWeagkDuQdlLg4gMLUWfu6ZL191hVskzHKdBssx5FxnWl8doRJidJg0E2GLo9LYHkfBIZei9qSOiEoqc4HA0YZDRAmmGJICgWjwHuP+2FSGmTB3Y=
  - secure: ZDhr59mnqz/d3AlOJAEZUai1Ursi4+XN4iXFs42Ee8ANpXeqlDZGuzOHcvPlxZtk5AhTeQBKAiTkRFleu6Siwx4rqSG2xslurlqIXw6my/kvZqD/+96VSoyBCYkl6szGkogW2wuHutq6e1QI0TciGZ2MnqxUDFVow7WrSEib4JI=
  - secure: UelzvKL+PzCd4c8SKO5seurlbs/Qf8JDDWZbWTH6Yl5cihTu3kD0zU7ERiEdMTC/sXubxrUpJqDR4pfXLhAXls9nC1wLFWz9Fyr5QTqWYlSdAWZZXvRAeyhgl9QohLJdtYaAJug2MY0m8PHJ6EiDMKiejhyUGPfP49EBsNBlCw4=
  - secure: SSv6tVU4XAkRasWgEv1TibepDxNYwv8BzCFvp0/BTC9d9nCawb4RyxR7+C/efNXyeoWohhaBGMgRM2ZjE1BuTlO4vrz/PQOHyrkv+wUAaiZ0AFjd2KXDRlpM3N7NY16vIEJ+pxUPb7jySEWWDWxf6oZeNG6wwrVnhZ6dlmrSyT4=
  - secure: X2GAc4AIbCLZQlOt5zvG1/uu8eRUSSgnNF75x9EXbS6YvXtUODEMFAYMP5CkxzSp+tF1vQxpbT82odVRJek7sVGJvf9ifl1NEfFdxewV1Kus9s5G/JTyIZlySTyvtNW2HrJLdfn3eBXdpVlosYLmzcz3MMq1jnJYb0UeraoZiNo=
  - secure: fL/nQcrs51PeJ50e0MunYdD7hcqMnd+cmib5RZDMfjUdK2nTmYoW/WfMh/uAA80twR4KSk2Gtk6/pIUnRtDhwClzIwaptyCs7zmPguchdJjYPkU6HL9ssflWjqsN9DxXBzmoWFTth1URSHcIWXboyl9TdXGkXSDsUHi48pwIH6Q=
  - secure: WQTipQntCPh83KKg1EQ1wSHKhriPp0DPzHhhZaFhm5WHhmRXYohM/tSx+Gl663mtAZ7uvEwJ5NXvGn/yODDxmiceqQnvhIPApBkBSGRQ75CFaH6em4+oNrKUnYT3wBOzwNWCgESRh0GQ7w7yzJe70X32QjjGsn3jeu293aDu+Ec=
  - secure: ca83BB84Ac5Fr/yGU7+kqTzLFK7porE7ZogWkOMHPJhF5dn66F5oHL9zT98tT7TGoJFBkWHhT8tAut6eUO+8MEfJzXSJpxAnbwj9sMRbnlKBBgnHIu5xqXhoJ7cIwwoT5dMK+tgvc6TENSLAm43qPcKUklF2tqJWHzQiWfXYBUY=
  - secure: btZbkdW+qOG2HL9j1cpA42Ny2HefW3LW/y83L/cRoNrY6fWXXz3Yf/SBscUJNJd5r5GrtHXpFeLNg2QPDQcCKktgGB+sx01XDinohcJQ64Mi8JbVn4HkgvV3Wl9AQvIjMkSxLYvn275sWz30IT+XwfgaOX45knXqHGiU4Fv3ZCc=
