"""empty message

Revision ID: 8ea53a70ea4
Revises: None
Create Date: 2014-07-19 21:28:56.724122

"""

# revision identifiers, used by Alembic.
revision = '8ea53a70ea4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('type', sa.String(length=2), nullable=True),
    sa.Column('vendor', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('uploaded_date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('migrate_version')
    op.drop_table('resources')
    op.alter_column('users', 'company',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'notes',
               existing_type=sa.VARCHAR(length=4000),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('users', 'resource',
               existing_type=sa.VARCHAR(length=4000),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('users', 'resource',
               existing_type=sa.VARCHAR(length=4000),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'notes',
               existing_type=sa.VARCHAR(length=4000),
               nullable=False)
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'company',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.create_table('resources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=400), nullable=False),
    sa.Column('type', sa.VARCHAR(length=1), nullable=False),
    sa.Column('vendor', sa.VARCHAR(length=20), nullable=False),
    sa.Column('url', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('uploaded_date', sa.DATETIME(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('repository_id')
    )
    op.drop_table('Resources')
    ### end Alembic commands ###
